<center><img src="https://github.com/insaid2018/Term-1/blob/master/Images/INSAID_Full%20Logo.png?raw=true" width="240" height="100" /></center>

# <center><b>Data Operations with Numpy<b></center>

---
# **Table of Contents**
---

**1.** [**Introduction to Numpy**](#Section1)<br>
**2.** [**Installing & Importing Libraries**](#Section2)<br>
  - **2.1** [**Installing Libraries**](#Section21)
  - **2.2** [**Importing Libraries**](#Section22)

**3.** [**Speed Check**](#Section3)<br>
**4.** [**Creating Numpy Arrays**](#Section4)<br>
**5.** [**Checking the Array Attributes**](#Section5)<br>
**6.** [**Array Initialization**](#Section6)<br>
**7.** [**Array Initialization using Random Numbers**](#Section7)<br>
**8.** [**Numpy Indexing**](#Section8)<br>
  - **8.1** [**Array Slicing**](#Section81)
  - **8.2** [**Conditional Array Indexing**](#Section82)

**9.** [**Numpy Array Operations**](#Section9)<br>
  - **9.1** [**Numpy Broadcasting**](#Section91)
  - **9.2** [**Numpy Mathematical Functions**](#Section92)
  - **9.3** [**Array Manipulation**](#Section93)
    - **9.3.1** [**Array Shape Manipulation**](#Section931)
    - **9.3.2** [**Array Merging & Splitting**](#Section932)

**10.** [**Conclusion**](#Section10)<br>


---
<a name = Section1></a>
# **1. Introduction to Numpy**
---

- **Numpy** is a library developed for Python which can handle large, multi-dimensional arrays and matrices. 

- It has a large **collections of mathematical functions** to operate on these arrays.

<center><img src="https://upload.wikimedia.org/wikipedia/commons/3/31/NumPy_logo_2020.svg"></center>

- It is **remarkably faster** than Python Lists for many reasons.

- It was designed for __efficient data storage__. All the elements of numpy arrays are stored __sequentially__ with a fixed width for each value. 

- On the other hand Lists are pointers to data stored elsewhere. The number of separate reads the computer has to do is smaller for numpy.

- Numpy has __uniform datatypes__ instead of Lists. The computer performs a logic for each different element type. 

- Due to this reason numpy completely avoids the extra computation.

- Numpy has __optimized functions__ for many mathematical operations on arrays and matrices. 

- This is the reason they are faster than regular math operations on lists.


---
<a name = Section2></a>
# **2. Installing & Importing Libraries**
---

- To refer to the official documentation of Numpy click <a href="https://numpy.org/doc/stable/">**here**</a>.

<a name = Section21></a>
### **2.1 Installing Libraries**

In [ ]:
!pip install -q --upgrade numpy

<a name = Section22></a>
### **2.2 Importing Libraries**

- We can give an alias name of np, so that we dont have to repeatedly use the longer form of the name.

In [2]:
import numpy as np                                                  # Importing package numpys (For Numerical Python)
import time                                                         # Importing time package

---
<a name = Section3></a>
# **3. Speed Check**
---

- In this section, we will perform speed comparison between Python Lists and Numpy.

In [3]:
size_of_vec = 1000000

def pure_python_version():                                                # This function will return the time for python calculation
    time_python = time.time()                                             # Start time before operation
    my_list1 = range(size_of_vec)                                         # Creating a list with 1000000 values
    my_list2 = range(size_of_vec)
    sum_list = [my_list1[i] + my_list2[i] for i in range(len(my_list1))]  # Calculating the sum
    return time.time() - time_python                                      # Return Current time - start time

def numpy_version():                                                      # This function will return the time for numpy calculation
    time_numpy = time.time()                                              # Start time before operation
    my_arr1 = np.arange(size_of_vec)                                      # Creating a numpy array of 1000000 values
    my_arr2 = np.arange(size_of_vec)
    sum_array = my_arr1 + my_arr2                                         # Calculate the sum
    return time.time() - time_numpy                                       # Return current time - start time


python_time = pure_python_version()                                       # Time taken for Python expression
numpy_time = numpy_version()                                              # Time taken for numpy operation
print("Pure Python version {:0.4f}".format(python_time))
print("Numpy version {:0.4f}".format(numpy_time))
print("Numpy is in this example {:0.4f} times faster!".format(python_time/numpy_time))

Pure Python version 0.2556
Numpy version 0.0127
Numpy is in this example 20.0499 times faster!


**Observations:**

- We observed that Numpy is way more faster than Python list.

- Also its more convenient when handling large datasets at once.

---
<a name = Section4></a>
# **4. Creating Numpy Arrays**
---

- The key feature of numpy is its N-dimensional array or ndarray, having the below specialities:

- It is **fast** and **flexible** container for large datasets in Python.

- These arrays **enable** you to carry **mathematical operations** on whole block of data.

- It is a **generic multi-dimensional container** for data, where each element is of the same type. 

- Below we will see some examples of ndarray showing 1D, 2D and 3D arrays:

<center><img src=""></center>

In [8]:
# Creating python list
my_list = [1, 2, 3, 4, 5]

# Dispaly the type of my_list variable
print('Type:', type(my_list))

# Output python list values
my_list

Type: <class 'list'>


[1, 2, 3, 4, 5]

In [9]:
# Creating 1-dimensional array using python list declared earlier
arr = np.array(my_list)

# Dispaly the type of arr variable
print('Type:', type(arr))

# Output array values
arr

Type: <class 'numpy.ndarray'>


array([1, 2, 3, 4, 5])

In [ ]:
[1,2]
[[1,2],[3,4]]
[[[0.5,0.5],[0.5,0.5,0.5,0.5]],[[0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5],[0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5]]]

[[[0.5, 0.5], [0.5, 0.5, 0.5, 0.5]],
 [[0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5],
  [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5]]]

In [11]:
# Creating a python list containing sub-lists of values
my_mat = [[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]]

# Creating 2-dimensional array using python list of my_mat
mat = np.array(my_mat) 

# Dispaly the type of mat variable
print('Type:', type(mat))

# Output array values
mat

Type: <class 'numpy.ndarray'>


array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

**Observation:**

- Numpy arrays have the same functionalities as Python lists but the difference lies in their functionality and speed of doing operations.

- The important diference in working with Numpy arrays is its more __convenient and fast__.

- ndarrays are widely used for __handling images__ as huge matrices of numbers.

- And its easier and faster to do any image operations in numpy arrays as compared to Python lists.

---
<a name = Section5></a>
# **5. Checking the Array Attributes**
---

- You might be interested to know the shape, dimensionality and datatype of the elements in the ndarray.

- Here are some numpy functions to know these attributes:
  - **.shape:** It gives the information about the dimensions of an ndarray.

  - **.ndim:** It gives the information about the resolution of an ndarray.

  - **.dtype:** It gives the information about the type or layout of data being stored by ndarray.

In [5]:
# Dispaly the type of arr variable
print('Type:', type(arr))

# Output array values
arr

array([1, 2, 3, 4, 5])

In [13]:
# Creating a python list containing sub-lists of values
my_mat = [[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]]

# Creating 2-dimensional array using python list of my_mat
mat = np.array(my_mat) 

# Output array values
mat

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [14]:
# Display the array and matrix shape
print('Array Shape:', arr.shape)
print('Matrix Shape:', mat.shape)

Array Shape: (5,)
Matrix Shape: (4, 3)


In [15]:
# Display the resolution of an array and matrix
print('Array Resolution:', arr.ndim)
print('Matrix Resolution:', mat.ndim)

Array Resolution: 1
Matrix Resolution: 2


In [16]:
# Display the type of the ndarray
print('Type of information stored in an array:', arr.dtype)
print('Type of information stored in a matrix :', mat.dtype)

Type of information stored in an array: int64
Type of information stored in a matrix : int64


**Observation:**

- We have seen how easy it is to make use of shape, ndim and dtype function to check the shape, dimension and datatype of the array.

---
<a name = Section6></a>
# **6. Array Initialization**
---

- In this section, we will learn some array initalization methods such as:

  - **.arange():** Generates an array of specifed range, step size (default is 1) and type of data to be stored.

  - **.zeros():** Generate an array containing zero values.

  - **.ones():** Generates an array containing ones as value.

  - **.linspace():** Generates an evenly spaced numbers over a specified interval.

  - **.eye():** Generates a 2-D array with ones on the diagonal and zeros elsewhere.

In [17]:
# Generating an array of size 10 with a step size of 1
np.arange(0, 10, 1, dtype=None)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
# Generating an array of size 10 with a step size of 2
np.arange(0, 10, 2, dtype=None)

array([0, 2, 4, 6, 8])

In [19]:
# Generates an array of size 4 containing zeros
np.zeros(shape=4)     

array([0., 0., 0., 0.])

In [20]:
# Generates an array of size 3 X 3 containing zeros
two_dim_zeros = np.zeros(shape=(3, 3))

# Display the resolution of two_dim_zeros variable
print('Resolution:', two_dim_zeros.ndim)

# Output the result
two_dim_zeros

Resolution: 2


array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [21]:
# Generates an array of size 3 X 3 containing ones
np.ones(shape=(3, 3)) 

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [22]:
# Generates an evenly spaced numbers from 0 to 5
np.linspace(start=0, stop=5, num=10)  

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [24]:
# Generates a 2-D array with ones on the diagonal and zeros elsewhere
np.eye(N=3, M=3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

---
<a name = Section7></a>
# **7. Random Array Initialization**
---

- In this section we are going to see how to populate array with random numbers.

- We will get to know about the following two function of numpy:

  - **.random.rand():** Create an array of the given shape and populate it with random samples from a uniform distribution over [0, 1).

  - **.random.randn():** Return a sample (or samples) from the “standard normal” distribution of mean 0 and variance 1.

In [ ]:
# Generates an array of 5 random values
np.random.rand(5)    

array([0.17803724, 0.09026592, 0.6789076 , 0.84240379, 0.44147801])

In [25]:
# Generates an array of random values having resolution of 2 X 2
np.random.rand(2, 2)  

array([[0.39867485, 0.99115341],
       [0.79008764, 0.77842722]])

In [26]:
# Generates an array of random values having resolution of 4 X 4
np.random.randn(4, 4)  

array([[ 0.50378675,  1.63723068,  1.23096018, -0.34940844],
       [-1.66395478, -0.6623835 ,  0.75369945, -3.85832612],
       [ 2.24225152,  0.93342862, -1.28922525,  0.84522516],
       [ 0.29653437,  0.28215221, -0.12912685,  0.52423076]])

In [38]:
# Generates an array of 6 random values
rand_array = np.random.rand(6)

# Display array containing random values
print('Random Array', rand_array)

# Display the resolution of the rand_array variable
print('Array Resolution:', rand_array.ndim)

# Reshape the 1-D array to 3 X 2 array and output the result
rand_array.reshape(3, 2) 

Random Array [0.44028078 0.33384475 0.54232089 0.16879632 0.16875282 0.51248866]
Array Resolution: 1


array([[0.44028078, 0.33384475],
       [0.54232089, 0.16879632],
       [0.16875282, 0.51248866]])

**Observation:**

- In various applications(like assigning weights in **Artificial Neural Networks**) arrays need to be initialized randomly.

- For this purpose there are various predefined functions in Numpy, and we have just seen how to make use of reshape and rand functions.

---
<a name = Section8></a>
# **8. Numpy Indexing**
---

- In this section we will show how numpy based elements are indexed and how to access these elements.

In [45]:
# Creating an array of 10 values ranging from 0 to 11
my_arr = np.arange(0, 11, 1)

# Display the array elements
print('Full Array:', my_arr)

# Display the element present at index 1
print('First element:', my_arr[1])

Full Array: [ 0  1  2  3  4  5  6  7  8  9 10]
First element: 1


**Observation:**

- We just saw that we can access individual elements of an array by calling them by their indices.

<a name = Section81></a>
## **8.1 Array Slicing**

- To access more than one element of an array use slicing operations.

In [49]:
# Creating an array of 10 values ranging from 0 to 11
my_arr = np.arange(0, 11, 1)

# Display the array elements
print('Full Array:', my_arr)

Full Array: [ 0  1  2  3  4  5  6  7  8  9 10]


In [50]:
# Accessing elements ranging from index 1 to 5
my_arr[1:5]

array([1, 2, 3, 4])

- **Note:** The first element that is extracted is of index 1 and the last element to be extracted is of index 5-1=4.

In [51]:
# Accessing elements ranging from index 8 onwards
my_arr[8:]

array([ 8,  9, 10])

In [52]:
# Accessing elements ranging till index 6
my_arr[:6]

array([0, 1, 2, 3, 4, 5])

- **Note:** Numpy arrays are **mutable**. It implies that you can change the values of the array.

In [53]:
# Mapping value -5 ranging index 0 to 5
my_arr[0:5] = -5 

# Output the array values
my_arr

array([-5, -5, -5, -5, -5,  5,  6,  7,  8,  9, 10])

- You can also perform slicing operations on 2-D array.

In [54]:
# Initializing an array of resolution 4 X 3
# It could also be achieved using arange(0, 12), and then using reshape(4, 3)
arr_2d = np.array([[0, 1, 2], 
                   [3, 4, 5], 
                   [6, 7, 8], 
                   [9, 10, 11]])

# Ouput the 2-D array
arr_2d

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [56]:
# Accessing element present at 0th row and 2nd column
arr_2d[0, 2]

2

In [57]:
# Accessing elements from rows (1st and 2nd) and columns (1st and 2nd)
arr_2d[0:2, 0:2]

array([[0, 1],
       [3, 4]])

In [58]:
# Accessing elements from rows (till 2nd) and columns (1st onwards)
arr_2d[:2, 1:]

array([[1, 2],
       [4, 5]])

**Observation:**

- So, through these examples we have seen that we can access one or multiple elements of an array using slicing.

- Also at times when needed we can extract subarrays from an array.

<a name = Section82></a>
## **8.2 Conditional Array Indexing**

- Here, we will observe how to **filter** element of an **array** based on some conditions.

- First, we need to create a **boolean array** based on an conditional statement using **conditional operators** for comparison.

- Then this boolean array is passed as index of the original array to return the filtered elements.

In [60]:
# Create a list of elements
arr = [1, 2, 3, 4, 5]

# Cast to numpy array
array = np.array(object=arr)

# Display the array elements
print('Elements:', array)

# Output boolean values (True for element greater than 2)
array > 2

Elements: [1 2 3 4 5]


array([False, False,  True,  True,  True])

In [67]:
# Initialize an array ranging from 2 to 15
arr = np.arange(2, 15)

# Display the elements of an array
print('Array:', arr)

# Display the lenght of array
print('Array Length:', len(arr))

Array: [ 2  3  4  5  6  7  8  9 10 11 12 13 14]
Array Length: 13


In [62]:
# Example 1: Output elements that have True as condition
arr[[True, False, True, False, True, False, False, False, False, False, False, False, False]]

array([2, 4, 6])

In [63]:
# Example 2: Output elements that have True as condition
arr[[False, False, False, False, False, False, False, True, True, True, True, True, True]]

array([ 9, 10, 11, 12, 13, 14])

In [65]:
# Output boolean values (True for element greater than 8)
arr > 8

array([False, False, False, False, False, False, False,  True,  True,
        True,  True,  True,  True])

In [66]:
# Output actual values based on the condition passed (elements greater than 8)
arr[arr > 8]

array([ 9, 10, 11, 12, 13, 14])

In [68]:
# Output values present at index 1 and 4
arr[[1, 4]]

array([3, 6])

In [70]:
# Output elements that have True as condition
arr[[False, True, False, False, True, False, False, False, False, False, False, False, False]]

array([3, 6])

**Observation:**

- Use conditional indexing to filter out some values like null or outliers in an array.

- Given below is a table where you can see what are the various operators available in Python.

<center><img src="https://www.oreilly.com/library/view/visual-basic-2012/9781118332085/images/f253-01.jpg"></center>

---
<a name = Section9></a>
# **9. Numpy Array Operations**
---

- In this section we will observe various arithmatic operations on numpy arrays.

<a name = Section91></a>
## **9.1 Numpy Broadcasting**

- The term broadcasting describes **how numpy treats arrays** with **different shapes** during arithmetic operations. 

- Subject to certain constraints, the smaller array is “broadcast” across the larger array so that they have compatible shapes.

- Broadcasting provides a means of **vectorizing array operations** so that looping occurs in C instead of Python. 

- It does this **without** making **needless copies of data** and usually leads to efficient algorithm implementations. 

- There are, however, cases where broadcasting is a bad idea because it leads to inefficient use of memory that slows computation.

- NumPy operations are usually done on pairs of arrays on an element-by-element basis. 

- In the simplest case, the two arrays must have exactly the same shape, as in the following example:

In [71]:
# First array of three elements
a = np.array([1.0, 2.0, 3.0])

# Second array of three elements
b = np.array([2.0, 2.0, 2.0])

# Output multiplication of arrays
a * b

array([2., 4., 6.])

- NumPy’s broadcasting rule relaxes this constraint when the arrays’ shapes meet certain constraints. 

- The simplest broadcasting example occurs when an array and a scalar value are combined in an operation:

In [72]:
# An array of three elements
a = np.array([1.0, 2.0, 3.0])

# Initialize variable with scalar value
b = 2.0

# Output the result of broadcasting
a * b

array([2., 4., 6.])

- **Note:** To know more about the **general broadcasting rules** click <a href="https://numpy.org/doc/stable/user/basics.broadcasting.html#general-broadcasting-rules">**here**</a>.

In [79]:
# Initialized array of resolution 4 X 3
arr_2d = np.array([[1, 2, 3], [5, 6, 7], [8, 9, 10], [12, 13, 14]])

# Initialize scaler with a constant value
scalar = 3

# Display the shape of 2-D array
print('Shape of Array:', arr_2d.shape)

# Output the 2-D array
arr_2d

Shape of Array: (4, 3)


array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 8,  9, 10],
       [12, 13, 14]])

In [80]:
# Output of broadcasting scalar value to the array
arr_2d + scalar

array([[ 4,  5,  6],
       [ 8,  9, 10],
       [11, 12, 13],
       [15, 16, 17]])

**Observation:**

- We can observe that scalar is stretched and is added to all of the elements of an array.

In [81]:
# Initialized 1-D array
arr_1d = np.array([10, 10, 10])

# Display the shape of 1-D array
print('Shape of Array:', arr_1d.shape)

# Output the 1-D array
arr_1d

Shape of Array: (3,)


array([10, 10, 10])

In [82]:
# Ouput broadcasted values to the 2-D array
arr_2d + arr_1d 

array([[11, 12, 13],
       [15, 16, 17],
       [18, 19, 20],
       [22, 23, 24]])

**Observation:**

- We observed that array with lower dimension i.e. arr_1d is stretched such that it matches the dimensions of arr_2d.

- Let's learn it better with one diagramatic example.

<center><img src="https://github.com/insaid2018/Term-1/blob/master/Images/broadcasting.png?raw=true"></center>

- From the above image you can see how and when the **data** is **stretched** to carry out the mathematical operations. 

- Here we have performed addition on arrays of varying dimensions. Always Remember to stretch the data as per the __broadcasting rules.__

- Now lets look at a different shape of array.

In [83]:
# Initialized 2-D array
arr = np.array([[1, 1, 1, 1]])

# Display the shape of 2-D array
print('Shape of Array:', arr.shape)

# Output the 2-D array
arr

Shape of Array: (1, 4)


array([[1, 1, 1, 1]])

In [84]:
# Ouput broadcasted values to the 2-D array
arr_2d + arr

ValueError: ignored

**Observation:**

- If the **dimensions do not match** it will **throw** an **exception**.

- It is **advisable** to **keep a note of the shape** or dimension of the arrays before applying any mathematical operation.

- And make sure they satisfy the broadcasting rules else value error may occur.

<a name = Section92></a>
## **9.2 Numpy Mathematical Functions**

- In this section we will observe faster and optimized mathematicalfunctions that we can apply for large size arrays.

- We will try out following functions with respect to an array:

  - **.min():** Return the minimum along a given axis.

  - **.max():** Return the maximum along a given axis.

  - **.argmin():** Returns the indices of the minimum values along an axis.

  - **.argmax():** Returns the indices of the maximum values along an axis.

  - **.sqrt():** Return the non-negative square-root of an array, element-wise.

  - **.mean():** Compute the arithmetic mean along the specified axis.

  - **.exp():** Calculate the exponential of all elements in the input array.

In [85]:
# Initialize an array of elements ranging from 1 to 11
arr = np.arange(1, 11)

# Output the array
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [91]:
print('Minimum value in an array:', arr.min())
print('Maximum value in an array:', arr.max())
print('Minimum index in an array:', arr.argmin())
print('Maximum index in an array:', arr.argmax())
print('Mean of an array:', arr.mean())

Minimum value in an array: 1
Maximum value in an array: 10
Minimum index in an array: 0
Maximum index in an array: 9
Mean of an array: 5.5


In [92]:
print('Square Root of elements in an array:', np.sqrt(arr))
print('Exponent of elements in an array:', np.exp(arr))

Square Root of elements in an array: [1.         1.41421356 1.73205081 2.         2.23606798 2.44948974
 2.64575131 2.82842712 3.         3.16227766]
Exponent of elements in an array: [2.71828183e+00 7.38905610e+00 2.00855369e+01 5.45981500e+01
 1.48413159e+02 4.03428793e+02 1.09663316e+03 2.98095799e+03
 8.10308393e+03 2.20264658e+04]


**Observation:**

- We saw various methods to do various mathematical operations like minimum, maximum, finding mean, finding exponent.

- There are more functions available to calculate various statistical parameters.

<a name = Section93></a>
## **9.3 Array Manipulation**

- In this section we will see some numpy functions that can change the structure (shape) of an array.

<a name = Section931></a>
### **9.3.1 Array Shape Manipulation**

- We will explore following functions that will perform array shape manipulation:

  - **.reshape():** Gives a new shape to an array without changing its data.

  - **.flatten():** Return a copy of the array collapsed into one dimension.

  - **.transpose()**: Reverse or permute the axes of an array and returns the modified array.

In [93]:
# Initialize an array of elements ranging from 0 to 116
arr = np.arange(0, 16)

# Output the array
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [94]:
# Reshaping array with resolution of 4 X 4 
arr_2D = arr.reshape(4, 4)

arr_2D

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
# Transform 2-D array to 1-D array
arr_2D.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [95]:
# Transpose the elements of 2-D array
arr_2D.transpose()

array([[ 0,  4,  8, 12],
       [ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 15]])

<a name = Section932></a>
### **9.3.2 Array Merging and Splitting**

- We will explore following functions that will perform array merging and splitting:

  - **.concatenate():** Join a sequence of arrays along an existing axis.

  - **.hsplit():** Split an array into multiple sub-arrays horizontally (column-wise).

  - **.vsplit():** Split an array into multiple sub-arrays vertically (row-wise).

In [97]:
# Initialize a first 2-D array of shape 2 X 4
arr_x = np.array([[1, 2, 3, 4], 
                  [5, 6, 7, 8]])

# Initialize a second 2-D array of shape 2 X 4
arr_y = np.array([[21, 22, 23, 24], 
                  [25, 26, 27, 28]])

In [102]:
# Concatenation of two 2-D arrays column-wise
concat_col_wise = np.concatenate((arr_x, arr_y), axis=1)

# Output the result of concatenation of two 2-D arrays column-wise
concat_col_wise

array([[ 1,  2,  3,  4, 21, 22, 23, 24],
       [ 5,  6,  7,  8, 25, 26, 27, 28]])

In [101]:
# Concatenation of two 2-D arrays row-wise
concat_row_wise = np.concatenate((arr_x, arr_y), axis=0)

# Output the result of concatenation of two 2-D arrays row-wise
concat_row_wise

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [21, 22, 23, 24],
       [25, 26, 27, 28]])

In [106]:
# Split an array into multiple sub-arrays horizontally (column-wise)
horizontal = np.hsplit(ary=concat_row_wise, indices_or_sections=2)

# Output the result
horizontal

[array([[ 1,  2],
        [ 5,  6],
        [21, 22],
        [25, 26]]), array([[ 3,  4],
        [ 7,  8],
        [23, 24],
        [27, 28]])]

In [107]:
# Split an array into multiple sub-arrays horizontally (column-wise)
verticle = np.vsplit(ary=concat_row_wise, indices_or_sections=2)

# Output the result
verticle

[array([[1, 2, 3, 4],
        [5, 6, 7, 8]]), array([[21, 22, 23, 24],
        [25, 26, 27, 28]])]

**Observation:**

- Using **concatenate** function we can merge arrays **columnwise** and **rowwise**. 

- Also arrays can be **horizontally** and **vertically** spliited using hsplit and vsplit.

---
<a name = Section10></a>
# **10. Conclusion**
---

- **Numpy** is an **open-source** add-on module to Python.

- By using Numpy you can **speed up** your **workflow** operations.

- You can **interface** with **other packages** in the Python ecosystem that use Numpy under the hood.

- A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays.

- It provides common mathematical and numerical routines in pre-compiled, fast functions.

- It **provides basic routines** for manipulating large arrays and matrices of numeric data.

- NumPy arrays have a fixed size decided at the time of creation. 

- Changing the size of an array will create a new array and delete the original.

- The **elements** in a NumPy array are all **required** to be of the **same data type**, and thus will be the same size in memory.

- NumPy arrays **facilitate advanced mathematical** and other types of **operations** on large numbers of data.

**<center><h2>That's All Folks!</h2></center>**